/// <reference types="next" />
/// <reference types="next/image-types/global" />
/// <reference path="./.next/types/routes.d.ts" />

// Generated by Next.js.
// See https://nextjs.org/docs/app/api-reference/config/typescript for details.
